# Generated by Django 6.0 on 2025-12-24 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_options_alter_income_options_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
