# Generated by Django 6.0 on 2025-12-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name_plural': 'expenses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name_plural': 'incomes'},
        ),
    ]
