# Generated by Django 6.0 on 2026-01-07 11:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category')},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='period',
        ),
    ]
